#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only OR MIT
"""Import only the named source constants from g17p_initdata.py, never captures."""
import argparse
import importlib.util
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("m1n1", type=Path)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
path = args.m1n1 / "proxyclient/m1n1/agx/g17p_initdata.py"
spec = importlib.util.spec_from_file_location("source", path)
source = importlib.util.module_from_spec(spec)
spec.loader.exec_module(source)
lines = [
    "// SPDX-License-Identifier: GPL-2.0-only OR MIT",
    "// Generated by tests/import_g17p_constants.py from g17p_initdata.py.",
    "// Named platform constants from the source ABI; no captured page bodies.",
    "",
]
for name in ("HWDATA_CONSTANTS", "REGION_C_CONSTANTS"):
    lines.append("#[rustfmt::skip]")
    lines.append(f"pub(crate) const {name}: &[(usize, &[u8])] = &[")
    for offset, data in getattr(source, name):
        values = ", ".join(f"0x{v:02x}" for v in data)
        lines.append(f"    (0x{offset:x}, &[{values}]),")
    lines.append("];\n")
out = Path(__file__).resolve().parent.parent / "g17p_constants.rs"
text = "\n".join(lines)
if args.check:
    assert out.read_text() == text, f"source constants differ: {out}"
    print("PASS: source ABI constants match the Python reference")
else:
    out.write_text(text)
