#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only OR MIT
"""Import the source-defined boot layout, never firmware or captured objects."""
import argparse
import importlib.util
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("m1n1", type=Path)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
spec = importlib.util.spec_from_file_location("source", args.m1n1 / "proxyclient/m1n1/agx/g17p.py")
src = importlib.util.module_from_spec(spec)
spec.loader.exec_module(src)
lines = [
    "// SPDX-License-Identifier: GPL-2.0-only OR MIT",
    "// Generated by tests/import_g17p_layout.py from g17p.py.",
    "// Source-defined ABI fields and constants, not captured object images.",
    "use super::g17p_abi::{Performance, Register};",
    "",
]

def constant(name, ty, value):
    lines.extend(["#[rustfmt::skip]", f"pub(crate) const {name}: {ty} = {value};", ""])

def value(v):
    if v is None:
        return "None"
    if isinstance(v, int):
        return hex(v)
    return "[" + ", ".join(value(n) for n in v) + "]"

names = (
    "SECONDARY_ROOT_DELTA", "NATIVE_PRIVATE_CLUSTER_OFFSET", "NATIVE_PRIVATE_CLUSTER_SIZE",
    "NATIVE_PRIMARY_WORK_STATE_OFFSET", "NATIVE_PRIMARY_STATUS_A_OFFSET",
    "NATIVE_SECONDARY_STATUS_A_OFFSET", "NATIVE_SECONDARY_WORK_STATE_OFFSET",
    "NATIVE_STATUS_B_OFFSET", "NATIVE_PRIMARY_STATUS_B_SIZE", "NATIVE_FWCTL_OFFSET",
    "NATIVE_PRIMARY_STATUS_B_CONFIG_HEADER", "NATIVE_PRIMARY_STATUS_B_CONFIG_OFFSET",
    "NATIVE_HWDATA_OFFSET", "NATIVE_PRIMARY_MAIN_OFFSET", "NATIVE_SECONDARY_MAIN_OFFSET",
    "NATIVE_SHARED_CLUSTER_SIZE", "NATIVE_PRIMARY_COMPUTED_PAGE_OFFSET", "NATIVE_ROOT_OFFSET",
    "MAIN_REPEATED_ADDR_OFFSET", "HWDATA_BUNDLE_STATE_PTR", "HWDATA_STATE_AFTER_CONTROL_STATE",
    "SECONDARY_EXTRA_ADDR_OBJECT", "SECONDARY_EXTRA_ADDR_OFFSET", "RING_STRIDE",
)
for name in names:
    constant(name, "usize", value(getattr(src, name)))
for name in ("NATIVE_WORK_STATE_OFFSETS", "NATIVE_WORK_RING_OFFSETS", "MAIN_ADDR_OBJECT_OFFSETS",
             "NATIVE_HWDATA_REGION_OFFSETS", "NATIVE_SECONDARY_ROOT_EXTRA_OFFSETS"):
    items = getattr(src, name)
    constant(name, f"[usize; {len(items)}]", value(items))
constant("ROOT_VERSION_VALUES", "[u16; 4]", value(src.ROOT_VERSION_VALUES))
assert src.PERF_TABLES["voltage_repeat"] == 16
constant("PERFORMANCE", "Performance", "Performance {\n" + "".join(
    f"    {name}: {value(values)},\n" for name, values in src.PERF_TABLES.items()
    if name != "voltage_repeat") + "}")
windows = []
for slot, phys, dva, size, echo, flag in src.REGISTER_WINDOWS:
    windows.append(f"    ({slot}, Register {{ physical: {phys:#x}, address: {dva:#x}, size: {size:#x}, relative: {echo:#x}, flags: {flag} }}),")
constant("REGISTERS", "&[(usize, Register)]", "&[\n" + "\n".join(windows) + "\n]")
constant("REGISTER_FLAGS", "&[(usize, u32)]", "&[" + ", ".join(f"({slot}, {flag})" for slot, flag in src.REGISTER_FLAG_ONLY_SLOTS.items()) + "]")
for name in ("NATIVE_PRIMARY_STATUS_B_CONFIG_RUNS", "NATIVE_SECONDARY_ROOT_EXTRA_1_RUNS"):
    constant(name, "&[(usize, &[u8])]", "&[\n" + "".join(
        f"    ({off:#x}, &{value(data)}),\n" for off, data in getattr(src, name)) + "]")
runs = list(src.HWDATA_BUNDLE_STATIC_RUNS)
for base, valid_size, obj in zip(src.MAIN_ADDR_OBJECT_OFFSETS, src.MAIN_ADDR_OBJECT_VALID_SIZES, src.MAIN_ADDR_OBJECTS):
    runs.extend((base + off, data) for off, data in obj["runs"] if off + len(data) <= valid_size)
constant("BUNDLE_RUNS", "&[(usize, &[u8])]", "&[\n" + "".join(
    f"    ({off:#x}, &{value(data)}),\n" for off, data in runs) + "]")
constant("TRAILING_STATES", "&[(usize, [Option<usize>; 3])]", "&[" + ", ".join(
    f"({index}, [" + ", ".join("None" if offset is None else f"Some({offset:#x})" for offset in offsets) + "])"
    for index, offsets in src.NATIVE_TRAILING_STATE_OFFSETS.items()) + "]")
constant("TRAILING_RINGS", "&[(usize, usize)]", "&[" + ", ".join(
    f"({index}, {offset:#x})" for index, offset in src.NATIVE_TRAILING_RING_OFFSETS.items()) + "]")
constant("PRIMARY_VIEWS", "[(usize, Option<u32>); 3]", "[" + ", ".join(
    f"({offset:#x}, " + ("None" if n is None else f"Some({n:#x})") + ")"
    for offset, n in src.NATIVE_PRIMARY_REGION_TRIPLES) + "]")
constant("SECONDARY_VIEWS", "[(u64, Option<u32>); 3]", "[" + ", ".join(
    f"({offset:#x}, " + ("None" if n is None else f"Some({n:#x})") + ")"
    for offset, n in src.SECONDARY_REGION_TRIPLES) + "]")
constant("REGION_SCALARS", "[(u32, u32, u32); 2]", "[" + ", ".join(
    f"({r['lead']:#x}, {r['value']:#x}, {r['trail']:#x})" for r in src.HWDATA_REGION_RECORDS) + "]")
out = Path(__file__).resolve().parent.parent / "g17p_layout.rs"
text = "\n".join(lines)
if args.check:
    assert out.read_text() == text, f"source boot layout differs: {out}"
    print("PASS: source boot layout matches the Python reference")
else:
    out.write_text(text)
